# Generated by Django 5.1 on 2025-10-28 00:27

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this tenant', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="HOA name (e.g., 'Sunset Hills HOA')", max_length=255)),
                ('schema_name', models.CharField(help_text="PostgreSQL schema name for data isolation (e.g., 'tenant_sunset_hills')", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Schema name must start with a letter and contain only lowercase letters, numbers, and underscores', regex='^[a-z][a-z0-9_]*$')])),
                ('primary_contact_name', models.CharField(blank=True, help_text='Primary board contact (e.g., Board President)', max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=20)),
                ('total_units', models.PositiveIntegerField(default=0, help_text='Total number of units/lots in this HOA')),
                ('address', models.TextField(blank=True, help_text='HOA mailing address')),
                ('state', models.CharField(blank=True, help_text='US state code (for state-specific lien rules)', max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('trial', 'Trial')], default='trial', help_text='Current tenant status', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this tenant was created')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When this tenant was activated (moved from trial to active)', null=True)),
                ('suspended_at', models.DateTimeField(blank=True, help_text='When this tenant was suspended (payment issues, etc.)', null=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Tenant-specific settings (timezone, date formats, etc.)')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['schema_name'], name='tenants_schema__8b4afe_idx'), models.Index(fields=['status'], name='tenants_status_80d9b6_idx'), models.Index(fields=['created_at'], name='tenants_created_fc84fe_idx')],
            },
        ),
    ]
