# Generated by Django 5.1 on 2025-10-28 00:50

from django.db import migrations


def seed_account_types(apps, schema_editor):
    """
    Seed the 5 standard account types with their normal balances.

    Normal balance rules:
    - Assets, Expenses: Debit (increases with debits)
    - Liabilities, Equity, Revenue: Credit (increases with credits)
    """
    AccountType = apps.get_model('accounting', 'AccountType')

    account_types = [
        {
            'code': 'ASSET',
            'name': 'Asset',
            'normal_balance': 'DEBIT',
            'description': 'Resources owned by the HOA (cash, accounts receivable, prepaid expenses)'
        },
        {
            'code': 'LIABILITY',
            'name': 'Liability',
            'normal_balance': 'CREDIT',
            'description': 'Obligations owed by the HOA (accounts payable, deferred revenue)'
        },
        {
            'code': 'EQUITY',
            'name': 'Equity',
            'normal_balance': 'CREDIT',
            'description': 'Fund balance and retained earnings'
        },
        {
            'code': 'REVENUE',
            'name': 'Revenue',
            'normal_balance': 'CREDIT',
            'description': 'Income earned by the HOA (assessments, late fees, interest)'
        },
        {
            'code': 'EXPENSE',
            'name': 'Expense',
            'normal_balance': 'DEBIT',
            'description': 'Costs incurred by the HOA (landscaping, utilities, insurance)'
        },
    ]

    for account_type_data in account_types:
        AccountType.objects.create(**account_type_data)


def reverse_seed(apps, schema_editor):
    """Remove seeded account types"""
    AccountType = apps.get_model('accounting', 'AccountType')
    AccountType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_account_types, reverse_seed),
    ]
