# Generated by Django 5.1 on 2025-10-28 03:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_invoice_status'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(help_text='Unique transfer number (e.g., TR-00001)', max_length=20, unique=True)),
                ('transfer_date', models.DateField(help_text='Date of the transfer')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transfer amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(help_text='Description/memo for the transfer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_fund', models.ForeignKey(help_text='Source fund (e.g., Operating)', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.fund')),
                ('journal_entry', models.OneToOneField(blank=True, help_text='Journal entry recording this transfer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_transfer', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(help_text='The HOA (tenant) this transfer belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='fund_transfers', to='tenants.tenant')),
                ('to_fund', models.ForeignKey(help_text='Destination fund (e.g., Reserve)', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.fund')),
            ],
            options={
                'db_table': 'fund_transfers',
                'ordering': ['-transfer_date', '-transfer_number'],
                'indexes': [models.Index(fields=['tenant', 'transfer_date'], name='fund_transf_tenant__2d7211_idx'), models.Index(fields=['from_fund', 'transfer_date'], name='fund_transf_from_fu_dd41a5_idx'), models.Index(fields=['to_fund', 'transfer_date'], name='fund_transf_to_fund_4e2683_idx')],
            },
        ),
    ]
