# Generated by Django 5.1 on 2025-10-28 03:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_fundtransfer'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export')], help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(help_text='Name of the model that was changed', max_length=100)),
                ('object_id', models.UUIDField(blank=True, help_text='ID of the object that was changed', null=True)),
                ('changes', models.JSONField(default=dict, help_text='Before/after values of changed fields')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this action occurred')),
                ('tenant', models.ForeignKey(help_text='The tenant this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', '-timestamp'], name='audit_logs_tenant__79c676_idx'), models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Tenant Admin'), ('manager', 'Property Manager'), ('accountant', 'Accountant'), ('board', 'Board Member')], help_text="User's role in this tenant", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='The tenant', on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(help_text='The user', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tenant_memberships',
                'indexes': [models.Index(fields=['user', 'tenant'], name='user_tenant_user_id_47ab36_idx'), models.Index(fields=['tenant', 'is_active'], name='user_tenant_tenant__7477e9_idx')],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
