# Generated by Django 5.1 on 2025-10-28 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auditlog_usertenantmembership'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Budget name (e.g., 'FY 2025 Operating Budget')", max_length=200)),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year for this budget')),
                ('start_date', models.DateField(help_text='Budget period start date')),
                ('end_date', models.DateField(help_text='Budget period end date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Budget notes and assumptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, help_text='Specific fund (null = all funds)', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.fund')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-fiscal_year', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, help_text='Budgeted amount for this account', max_digits=12)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes and assumptions for this budget line')),
                ('account', models.ForeignKey(help_text='Account this budget line applies to', on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.budget')),
            ],
            options={
                'db_table': 'budget_lines',
                'ordering': ['account__account_number'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', 'fiscal_year'], name='budgets_tenant__8e07e3_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', 'status'], name='budgets_tenant__acf4fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('tenant', 'fiscal_year', 'fund')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('budget', 'account')},
        ),
    ]
