# Generated by Django 5.1 on 2025-10-29 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_add_reserve_planning_models'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, help_text='User who created this report (username or email)', max_length=255)),
                ('name', models.CharField(help_text="Report name (e.g., 'Monthly AR Aging by Fund')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this report shows')),
                ('report_type', models.CharField(choices=[('GENERAL_LEDGER', 'General Ledger'), ('TRIAL_BALANCE', 'Trial Balance'), ('INCOME_STATEMENT', 'Income Statement'), ('BALANCE_SHEET', 'Balance Sheet'), ('CASH_FLOW', 'Cash Flow Statement'), ('AR_AGING', 'AR Aging Report'), ('OWNER_LEDGER', 'Owner Ledger'), ('BUDGET_VARIANCE', 'Budget Variance'), ('RESERVE_FUNDING', 'Reserve Funding Analysis')], help_text='Base report type', max_length=30)),
                ('columns', models.JSONField(default=list, help_text="List of columns to include: ['date', 'account', 'amount', etc.]")),
                ('filters', models.JSONField(default=dict, help_text="Report filters as JSON: {'fund': 'uuid', 'date_from': '2025-01-01', etc.}")),
                ('sort_by', models.JSONField(default=list, help_text="Sort order: [{'field': 'date', 'direction': 'desc'}]")),
                ('is_public', models.BooleanField(default=False, help_text='Whether this report is shared with all users in tenant')),
                ('is_favorite', models.BooleanField(default=False, help_text="User's favorite reports (shown at top)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'custom_reports',
                'ordering': ['-is_favorite', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_by', models.CharField(blank=True, help_text='User who executed this report', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, help_text='Number of rows returned', null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('result_cache', models.JSONField(blank=True, help_text='Cached result data (optional, for fast re-display)', null=True)),
                ('parameters', models.JSONField(default=dict, help_text='Runtime parameters (date ranges, overrides, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='accounting.customreport')),
            ],
            options={
                'db_table': 'report_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customreport',
            index=models.Index(fields=['tenant', 'report_type'], name='custom_repo_tenant__397761_idx'),
        ),
        migrations.AddIndex(
            model_name='customreport',
            index=models.Index(fields=['tenant', 'created_by'], name='custom_repo_tenant__9d5deb_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['report', '-started_at'], name='report_exec_report__a480d1_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['executed_by', '-started_at'], name='report_exec_execute_481199_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['status'], name='report_exec_status_c1b883_idx'),
        ),
    ]
