# Generated by Django 5.1 on 2025-10-29 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_add_violation_tracking_models'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPacketTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'Monthly Board Meeting')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('sections', models.JSONField(default=list, help_text="List of sections to include: ['agenda', 'financials', 'ar_aging', etc.]")),
                ('section_order', models.JSONField(default=list, help_text='Order of sections in packet')),
                ('include_cover_page', models.BooleanField(default=True, help_text='Include auto-generated cover page')),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'board_packet_templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoardPacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Packet title (e.g., 'November 2025 Board Meeting')", max_length=255)),
                ('meeting_date', models.DateField(help_text='Date of board meeting')),
                ('generated_date', models.DateTimeField(auto_now_add=True, help_text='When packet was generated')),
                ('generated_by', models.CharField(help_text='User who generated the packet', max_length=255)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('SENT', 'Sent')], default='GENERATING', max_length=20)),
                ('pdf_url', models.URLField(blank=True, help_text='URL to generated PDF (S3, CloudFlare, etc.)', max_length=500)),
                ('pdf_size_bytes', models.IntegerField(blank=True, help_text='PDF file size in bytes', null=True)),
                ('page_count', models.IntegerField(blank=True, help_text='Number of pages in PDF', null=True)),
                ('generation_time_seconds', models.IntegerField(blank=True, help_text='Time taken to generate PDF', null=True)),
                ('sent_to', models.JSONField(default=list, help_text='List of email addresses packet was sent to')),
                ('sent_date', models.DateTimeField(blank=True, help_text='When packet was emailed to board', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this packet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_packets', to='tenants.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packets', to='accounting.boardpackettemplate')),
            ],
            options={
                'db_table': 'board_packets',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='PacketSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('COVER_PAGE', 'Cover Page'), ('AGENDA', 'Meeting Agenda'), ('MINUTES', 'Previous Minutes'), ('FINANCIAL_SUMMARY', 'Financial Summary'), ('TRIAL_BALANCE', 'Trial Balance'), ('CASH_FLOW', 'Cash Flow Statement'), ('AR_AGING', 'AR Aging Report'), ('DELINQUENCY_REPORT', 'Delinquency Report'), ('VIOLATION_SUMMARY', 'Violation Summary'), ('RESERVE_SUMMARY', 'Reserve Study Summary'), ('BUDGET_VARIANCE', 'Budget Variance'), ('CUSTOM_REPORT', 'Custom Report'), ('ATTACHMENT', 'Attachment')], max_length=30)),
                ('title', models.CharField(help_text='Section title/heading', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('content_url', models.URLField(blank=True, help_text='URL to section content (PDF, image, etc.)', max_length=500)),
                ('content_data', models.JSONField(blank=True, help_text='Embedded content data (for reports generated inline)', null=True)),
                ('page_start', models.IntegerField(blank=True, help_text='Starting page number in final PDF', null=True)),
                ('page_end', models.IntegerField(blank=True, help_text='Ending page number in final PDF', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounting.boardpacket')),
            ],
            options={
                'db_table': 'packet_sections',
                'ordering': ['packet', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='boardpacket',
            index=models.Index(fields=['tenant', '-meeting_date'], name='board_packe_tenant__4c5abb_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpacket',
            index=models.Index(fields=['status'], name='board_packe_status_b57b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='packetsection',
            index=models.Index(fields=['packet', 'order'], name='packet_sect_packet__3ddf74_idx'),
        ),
    ]
