# Generated by Django 5.1 on 2025-10-31 17:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_arcrequesttype_arcrequest_arcreview_vendor_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Export title (e.g., '2025 Annual Audit Export')", max_length=200)),
                ('start_date', models.DateField(help_text='Beginning of date range')),
                ('end_date', models.DateField(help_text='End of date range')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF')], default='csv', help_text='Export file format', max_length=20)),
                ('include_evidence', models.BooleanField(default=True, help_text='Include links to supporting documents')),
                ('include_balances', models.BooleanField(default=True, help_text='Include running balances for each account')),
                ('include_owner_data', models.BooleanField(default=False, help_text='Include owner personal information (privacy flag)')),
                ('file_url', models.URLField(blank=True, help_text='URL to generated export file (S3 or local storage)', max_length=500)),
                ('file_size_bytes', models.IntegerField(default=0, help_text='File size in bytes')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash for integrity verification', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When export was generated')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', help_text='Export generation status', max_length=20)),
                ('downloaded_count', models.IntegerField(default=0, help_text='Number of times export was downloaded')),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Most recent download timestamp', null=True)),
                ('total_entries', models.IntegerField(default=0, help_text='Total journal entries in export')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all debit entries', max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all credit entries', max_digits=15)),
                ('evidence_count', models.IntegerField(default=0, help_text='Number of transactions with evidence links')),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_exports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_exports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'auditor_exports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['tenant', '-generated_at'], name='auditor_exp_tenant__927b8b_idx'), models.Index(fields=['start_date', 'end_date'], name='auditor_exp_start_d_631303_idx'), models.Index(fields=['status'], name='auditor_exp_status_6e9cbf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='auditor_export_valid_date_range'), models.CheckConstraint(condition=models.Q(('total_debit', models.F('total_credit'))), name='auditor_export_balanced')],
            },
        ),
    ]
