# Generated by Django 5.1 on 2025-10-31 (Sprint 22)

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_add_auditor_export_model'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleDisclosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('escrow_agent', models.CharField(blank=True, max_length=200)),
                ('escrow_company', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(help_text="State code (e.g., 'CA', 'TX', 'FL')", max_length=2)),
                ('template_version', models.CharField(default='v1.0', help_text='State template version', max_length=50)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('generating', 'Generating'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('pdf_size_bytes', models.IntegerField(default=0)),
                ('pdf_hash', models.CharField(blank=True, max_length=64)),
                ('page_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monthly_dues', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('special_assessments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('has_lien', models.BooleanField(default=False)),
                ('has_violations', models.BooleanField(default=False)),
                ('violation_count', models.IntegerField(default=0)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=15)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resale_disclosures', to='accounting.invoice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resale_disclosures', to='accounting.owner')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disclosure_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resale_disclosures', to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resale_disclosures', to='accounting.unit')),
            ],
            options={
                'db_table': 'resale_disclosures',
                'ordering': ['-requested_at'],
                'indexes': [
                    models.Index(fields=['tenant', '-requested_at'], name='resale_dis_tenant__idx'),
                    models.Index(fields=['unit'], name='resale_dis_unit_idx'),
                    models.Index(fields=['status'], name='resale_dis_status_idx'),
                    models.Index(fields=['state'], name='resale_dis_state_idx'),
                ],
            },
        ),
    ]
